/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAvailableAssessments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishAssessment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{snapshotId}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAssessmentConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{snapshotId}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAssessmentQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{snapshotId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startAssessment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and obtain JWT token */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/set-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set new password (first access or expired password) */
        post: operations["setPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCompetencies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["markAllAsRead"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/unread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUnread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["markAsRead"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["byTag"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{questionId}/tags/{tagId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["attachTag"];
        delete: operations["detachTag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMySubmissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{submissionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSubmission"];
        put: operations["submitAnswers"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{submissionId}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSavedAnswers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{submissionId}/answers/{questionSnapshotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["saveAnswer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{submissionId}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSubmissionQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{submissionId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSubmissionReview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOwn"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{tagId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch: operations["rename"];
        trace?: never;
    };
    "/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTopics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{topicId}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTopicChapters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/training/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startTraining"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfile"];
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNotifications"];
        put: operations["updateNotifications"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnswerInput: {
            motivation?: string;
            question_id: string;
            selected_option_ids?: string[];
            text?: string;
            type: string;
        };
        AnswerResult: {
            correct_option_snapshot_ids: string[];
            is_correct: boolean | null;
            /** Format: double */
            points_awarded: number | null;
            question_snapshot_id: string;
            type: string;
        };
        AssessmentConfigResponse: {
            assessmentId: string;
            availableFrom: string | null;
            availableUntil: string | null;
            /** Format: int32 */
            maxAttempts: number | null;
            /** Format: int32 */
            questionsPerAssessment: number;
            scoring: components["schemas"]["ScoringRules"];
            shuffleOptions: boolean;
            shuffleQuestions: boolean;
            subjects: components["schemas"]["SubjectDto"][];
            /** Format: int32 */
            timerMinutes: number;
            title: string;
        };
        AssessmentListItem: {
            availableFrom: string | null;
            availableUntil: string | null;
            difficulty: string | null;
            id: string;
            /** Format: int32 */
            questionsPerAssessment: number;
            /** Format: double */
            score: number | null;
            status: string;
            subjects: components["schemas"]["SubjectDto"][];
            /** Format: int32 */
            timerMinutes: number;
            title: string;
            type: string;
        };
        AssessmentListResponse: {
            assessments: components["schemas"]["AssessmentListItem"][];
            pagination: components["schemas"]["PaginationMetadata"];
        };
        AssessmentQuestionsResponse: {
            assessmentId: string | null;
            availableFrom: string | null;
            availableUntil: string | null;
            questions: components["schemas"]["QuestionDto"][];
            /** Format: int32 */
            timerMinutes: number;
            title: string;
            /** Format: int32 */
            totalQuestions: number;
        };
        AvailableQuestions: {
            /** Format: int32 */
            advanced: number;
            /** Format: int32 */
            base: number;
            /** Format: int32 */
            intermediate: number;
            /** Format: int32 */
            total: number;
        };
        ChangePasswordRequest: {
            confirm_password: string;
            current_password: string;
            new_password: string;
        };
        ChapterItem: {
            id: string;
            label: string;
            question_counts: components["schemas"]["QuestionCounts"];
        };
        CompetencyResponse: {
            topics: components["schemas"]["TopicMastery"][];
        };
        LoginRequest: {
            password: string;
            username: string;
        };
        LoginResponse: {
            must_change_password: boolean;
            password_expired: boolean;
            token: string;
            user: components["schemas"]["UserInfo"];
        };
        NotificationItemDto: {
            created_at: string | null;
            event: string;
            id: string;
            message: string;
            read: boolean;
            title: string;
        };
        NotificationPreferenceDto: {
            channel: string;
            enabled: boolean;
            event: string;
        };
        OptionDto: {
            id: string;
            isFallback: boolean;
            text: string;
        };
        PaginationMetadata: {
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            total_elements: number;
            /** Format: int32 */
            total_pages: number;
        };
        QuestionCounts: {
            /** Format: int32 */
            advanced: number;
            /** Format: int32 */
            base: number;
            /** Format: int32 */
            intermediate: number;
        };
        QuestionDto: {
            code: string | null;
            id: string;
            options: components["schemas"]["OptionDto"][] | null;
            /** Format: double */
            points: number | null;
            subjects: components["schemas"]["SubjectDto"][];
            text: string;
            type: string;
        };
        ReviewOption: {
            id: string;
            is_correct: boolean;
            /** Format: int32 */
            position: number;
            text: string;
        };
        ReviewQuestion: {
            answer_text: string | null;
            code: string | null;
            explanation: string | null;
            id: string;
            is_correct: boolean | null;
            motivation: string | null;
            options: components["schemas"]["ReviewOption"][];
            /** Format: double */
            points: number | null;
            /** Format: double */
            points_awarded: number | null;
            /** Format: int32 */
            position: number;
            selected_option_ids: string[];
            subjects: components["schemas"]["SubjectDto"][];
            text: string;
            type: string;
        };
        SaveAnswerRequest: {
            flagged?: boolean;
            motivation?: string;
            selected_option_ids?: string[];
            text?: string;
            type: string;
        };
        SavedAnswer: {
            flagged: boolean;
            motivation: string | null;
            question_snapshot_id: string;
            selected_option_ids: string[];
            text: string | null;
            type: string;
        };
        SavedAnswersResponse: {
            answers: components["schemas"]["SavedAnswer"][];
        };
        ScoringRules: {
            /** Format: double */
            pointsPerCorrect: number;
            /** Format: double */
            pointsPerUnanswered: number;
            /** Format: double */
            pointsPerWrong: number;
        };
        SetPasswordRequest: {
            confirm_password: string;
            new_password: string;
        };
        SubjectDto: {
            id: string;
            label: string;
        };
        SubjectMastery: {
            id: string;
            label: string;
            /** Format: int32 */
            mastery: number;
        };
        SubjectScore: {
            label: string;
            /** Format: double */
            points_available: number;
            /** Format: double */
            points_earned: number;
            subject_id: string;
        };
        SubmissionFeedbackResponse: {
            answers: components["schemas"]["AnswerResult"][];
            assessment_snapshot_id: string;
            id: string;
            /** Format: double */
            max_score: number | null;
            passed: boolean | null;
            /** Format: double */
            passing_score: number | null;
            /** Format: double */
            score: number | null;
            started_at: string | null;
            subject_scores: components["schemas"]["SubjectScore"][];
            submitted_at: string | null;
            user_id: string;
        };
        SubmissionHistoryResponse: {
            pagination: components["schemas"]["PaginationMetadata"];
            submissions: components["schemas"]["SubmissionSummary"][];
        };
        SubmissionReviewResponse: {
            assessment_title: string;
            id: string;
            /** Format: double */
            max_score: number | null;
            questions: components["schemas"]["ReviewQuestion"][];
            /** Format: double */
            score: number | null;
            started_at: string | null;
            submitted_at: string | null;
        };
        SubmissionStartResponse: {
            started_at: string;
            submission_id: string;
        };
        SubmissionSubmitRequest: {
            answers: components["schemas"]["AnswerInput"][];
        };
        SubmissionSummary: {
            assessment_snapshot_id: string;
            assessment_title: string;
            /** Format: int32 */
            correct_count: number;
            id: string;
            /** Format: double */
            max_score: number | null;
            passed: boolean | null;
            /** Format: double */
            score: number | null;
            started_at: string | null;
            subject_scores: components["schemas"]["SubjectScore"][];
            submitted_at: string | null;
            /** Format: int32 */
            total_questions: number;
            type: string;
            /** Format: int32 */
            unanswered_count: number;
            /** Format: int32 */
            wrong_count: number;
        };
        TagRequest: {
            name: string;
        };
        TagResponse: {
            id: string;
            name: string;
        };
        TaggedQuestionResponse: {
            id: string;
            /** Format: int32 */
            position: number;
            tags: components["schemas"]["TagResponse"][];
            text: string;
            type: string;
        };
        TopicChaptersResponse: {
            available_questions: components["schemas"]["AvailableQuestions"];
            chapters: components["schemas"]["ChapterItem"][];
            topic_id: string;
            topic_title: string;
        };
        TopicItem: {
            abbreviation: string | null;
            chapters: components["schemas"]["ChapterItem"][];
            description: string | null;
            enabled: boolean;
            id: string;
            title: string;
            /** Format: int32 */
            total_chapters: number;
            /** Format: int32 */
            total_questions: number;
        };
        TopicListResponse: {
            topics: components["schemas"]["TopicItem"][];
        };
        TopicMastery: {
            children: components["schemas"]["TopicMastery"][];
            id: string;
            /** Format: int32 */
            mastery: number;
            subjects: components["schemas"]["SubjectMastery"][];
            title: string;
        };
        TrainingStartRequest: {
            chapter_ids?: string[];
            difficulty?: string;
            /** Format: int32 */
            question_count: number;
            timer_enabled: boolean;
            topic_id?: string;
        };
        TrainingStartResponse: {
            submission_id: string;
            /** Format: int32 */
            timer_minutes: number | null;
            /** Format: int32 */
            total_questions: number;
        };
        UpdateNotificationPreferencesRequest: {
            preferences: components["schemas"]["NotificationPreferenceDto"][];
        };
        UpdateProfileRequest: {
            email?: string;
            language?: string;
        };
        UserInfo: {
            class_name: string;
            first_name: string;
            id: string;
            last_name: string;
            username: string;
        };
        UserProfileResponse: {
            class_name: string;
            email: string | null;
            first_name: string;
            id: string;
            language: string;
            last_name: string;
            role: string;
            username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAvailableAssessments: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AssessmentListResponse"];
                };
            };
        };
    };
    publishAssessment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAssessmentConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AssessmentConfigResponse"];
                };
            };
        };
    };
    getAssessmentQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AssessmentQuestionsResponse"];
                };
            };
        };
    };
    startAssessment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubmissionStartResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    setPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    getCompetencies: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CompetencyResponse"];
                };
            };
        };
    };
    getCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    markAllAsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getUnread: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotificationItemDto"][];
                };
            };
        };
    };
    markAsRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    byTag: {
        parameters: {
            query: {
                tagId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaggedQuestionResponse"][];
                };
            };
        };
    };
    attachTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
                tagId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    detachTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
                tagId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMySubmissions: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubmissionHistoryResponse"];
                };
            };
        };
    };
    getSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubmissionFeedbackResponse"];
                };
            };
        };
    };
    submitAnswers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionSubmitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubmissionFeedbackResponse"];
                };
            };
        };
    };
    getSavedAnswers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SavedAnswersResponse"];
                };
            };
        };
    };
    saveAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionId: string;
                questionSnapshotId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveAnswerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSubmissionQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AssessmentQuestionsResponse"];
                };
            };
        };
    };
    getSubmissionReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubmissionReviewResponse"];
                };
            };
        };
    };
    listOwn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TagResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TagResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tagId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rename: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tagId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TagResponse"];
                };
            };
        };
    };
    getTopics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TopicListResponse"];
                };
            };
        };
    };
    getTopicChapters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TopicChaptersResponse"];
                };
            };
        };
    };
    startTraining: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainingStartRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TrainingStartResponse"];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    getNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotificationPreferenceDto"][];
                };
            };
        };
    };
    updateNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNotificationPreferencesRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotificationPreferenceDto"][];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
